#!/usr/bin/env php
<?php

declare(strict_types=1);

$autoloadPaths = [
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../../autoload.php',
    dirname(__DIR__) . '/vendor/autoload.php',
    dirname(dirname(__DIR__)) . '/autoload.php',
    dirname(dirname(dirname(__DIR__))) . '/autoload.php',
];

$home = $_SERVER['HOME'] ?? getenv('HOME');
if ($home) {
    $autoloadPaths[] = $home . '/.config/composer/vendor/autoload.php';
    $autoloadPaths[] = $home . '/.composer/vendor/autoload.php';
}

$loaded = false;
foreach ($autoloadPaths as $path) {
    if (file_exists($path)) {
        require $path;
        $loaded = true;
        break;
    }
}

if (!$loaded) {
    fwrite(STDERR, "Run 'composer install' first.\n");
    exit(1);
}

$app = new \PakuaOS\Application\PakuaOS();
$app->boot();
$app->run();
