#!/usr/bin/env php
<?php

declare(strict_types=1);

$loaded = false;
$dir = __DIR__;

for ($i = 0; $i < 10; $i++) {
    $candidate = $dir . '/vendor/autoload.php';
    if (file_exists($candidate)) {
        require $candidate;
        $loaded = true;
        break;
    }
    $parent = dirname($dir);
    if ($parent === $dir) break;
    $dir = $parent;
}

if (!$loaded) {
    fwrite(STDERR, "Run 'composer install' first.\n");
    exit(1);
}

$app = new \PakuaOS\Application\PakuaOS();
$app->boot();
$app->run();
